# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
  - mkdir .deploy
  - cp -r * .deploy
  - mv .deploy deploy
  artifacts:
    paths:
    - deploy
  only:
  - master
